parameters:
#    keosu_data_model_quizz_model.example.class: Keosu\DataModel\QuizzModelBundle\Example

services:
#    keosu_data_model_quizz_model.example:
#        class: %keosu_data_model_quizz_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
