keosu_data_model_menu_model:
    resource: "@KeosuDataModelMenuModelBundle/Resources/config/routing.yml"
    prefix:   /

keosu_data_model_search_model:
    resource: "@KeosuDataModelSearchModelBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_push_notification:
    resource: "@KeosuGadgetPushNotificationBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_twitter_gadget:
    resource: "@KeosuGadgetTwitterGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_comment_gadget:
    resource: "@KeosuGadgetCommentGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_my_account_gadget:
    resource: "@KeosuGadgetMyAccountGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_authentication_gadget:
    resource: "@KeosuGadgetAuthenticationGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_pictures_gallery_gadget:
    resource: "@KeosuGadgetPicturesGalleryGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_picture_gadget:
    resource: "@KeosuGadgetPictureGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_data_model_picture_model:
    resource: "@KeosuDataModelPictureModelBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_around_me_gadget:
    resource: "@KeosuGadgetAroundMeGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_reader_rss_reader:
    resource: "@KeosuReaderRssReaderBundle/Resources/config/routing.yml"
    prefix:   /

keosu_readerics_reader:
    resource: "@KeosuReaderIcsReaderBundle/Resources/config/routing.yml"
    prefix:   /

keosu_reader_rss_event_reader:
    resource: "@KeosuReaderRssEventReaderBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_last_article_gadget:
    resource: "@KeosuGadgetLastArticleGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_article_gadget:
    resource: "@KeosuGadgetArticleGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_map_gadget:
    resource: "@KeosuGadgetMapGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_calendar_gadget:
    resource: "@KeosuGadgetCalendarGadgetBundle/Resources/config/routing.yml"
    prefix:   /

keosu_core:
    resource: "@KeosuCoreBundle/Resources/config/routing.yml"
    prefix:   /

keosu_article:
    resource: "@KeosuDataModelArticleModelBundle/Resources/config/routing.yml"
    prefix:   /

keosu_poi:
    resource: "@KeosuDataModelLocationModelBundle/Resources/config/routing.yml"
    prefix:   /

keosu_event:
    resource: "@KeosuDataModelEventModelBundle/Resources/config/routing.yml"
    prefix:   /

#FOS User route
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
login:
    path: /login
    defaults:
        _controller: KeosuUserBundle:Security:login
login_check:
    path: /login_check
logout:
    path: /logout

keosu_data_model_form_model:
    resource: "@KeosuDataModelFormModelBundle/Resources/config/routing.yml"
    prefix:   /

keosu_gadget_form_gadget:
    resource: "@KeosuGadgetFormGadgetBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
