parameters:
    keosu_core.exporter.class: Keosu\CoreBundle\Service\Exporter
    keosu_core.package_manager.class: Keosu\CoreBundle\Service\PackageManager
    keosu_core.curapp.class: Keosu\CoreBundle\Service\CurApp

services:
    keosu_core.exporter:
        class: %keosu_core.exporter.class%
        arguments: ['@doctrine','@service_container']
    keosu_core.package_manager:
        class: %keosu_core.package_manager.class%
        arguments: ['@service_container']
    keosu_core.curapp:
        class: %keosu_core.curapp.class%
        arguments: ['@doctrine','@session']
    keosu_core.image_type_extension:
        class: Keosu\CoreBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType  }
    keosu_core.twig.includepanelextension:
        class: Keosu\CoreBundle\Twig\TwigIncludePanelExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
    keosu_core.twig.appmenuextension:
        class: Keosu\CoreBundle\Twig\TwigMenuExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

