<?php
/************************************************************************
 Keosu is an open source CMS for mobile app
Copyright (C) 2016  Pockeit

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
************************************************************************/
namespace Keosu\Gadget\CommentGadgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository {
	
	/***
	 * Find all shared gadget in a zone for an app
	 */
	public function findCommentForModel($idDataModel,$dataModelObjectName) {

		$qb = $this->_em->createQueryBuilder();

		$qb->select('a')
			->from($this->_entityName, 'a')
			->where('a.dataModelObject = :dataModelObject')
			->andWhere('a.idDataModel = :idDataModel')
			->setParameter('dataModelObject',$dataModelObjectName)
			->setParameter('idDataModel',$idDataModel);

		return $qb->getQuery()
				  ->getResult(); 
	}
}
