services:
    keosu_gadget.quizz.gadget:
        class: Keosu\Gadget\QuizzGadgetBundle\EventListener\GadgetListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }

