<?php

namespace Keosu\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ManageReadersController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Keosu\CoreBundle\Controller\ManageReadersController();
        return $instance;
    }
}
