<?php

namespace CoreSphere\ConsoleBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ConsoleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CoreSphere\ConsoleBundle\Controller\ConsoleController();
        return $instance;
    }
}
