<?php

namespace FOS\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GroupController__JMSInjector
{
    public static function inject($container) {
        $instance = new \FOS\UserBundle\Controller\GroupController();
        return $instance;
    }
}
