<?php

namespace Keosu\Gadget\ArticleGadgetBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ServiceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Keosu\Gadget\ArticleGadgetBundle\Controller\ServiceController();
        return $instance;
    }
}
