<?php

namespace Keosu\DataModel\SearchModelBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EditController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Keosu\DataModel\SearchModelBundle\Controller\EditController();
        return $instance;
    }
}
