<?php

namespace Keosu\Gadget\AuthenticationGadgetBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ResetController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Keosu\Gadget\AuthenticationGadgetBundle\Controller\ResetController();
        return $instance;
    }
}
