<?php

namespace Proxies\__CG__\Keosu\DataModel\ArticleModelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArticleBody extends \Keosu\DataModel\ArticleModelBundle\Entity\ArticleBody implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'idext', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'title', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'body', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'author', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'date', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'version', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'attachments', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'tags', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'enableComments', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'shareUrl'];
        }

        return ['__isInitialized__', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'idext', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'title', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'body', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'author', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'date', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'version', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'attachments', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'tags', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'enableComments', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleBody' . "\0" . 'shareUrl'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ArticleBody $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdext($idext)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdext', [$idext]);

        return parent::setIdext($idext);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdext()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdext', []);

        return parent::getIdext();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setBody($body)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBody', [$body]);

        return parent::setBody($body);
    }

    /**
     * {@inheritDoc}
     */
    public function getBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBody', []);

        return parent::getBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor($author)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', [$author]);

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', []);

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnableComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnableComments', []);

        return parent::getEnableComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnableComments($enableComments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnableComments', [$enableComments]);

        return parent::setEnableComments($enableComments);
    }

    /**
     * {@inheritDoc}
     */
    public function setShareUrl($shareUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShareUrl', [$shareUrl]);

        return parent::setShareUrl($shareUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getShareUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShareUrl', []);

        return parent::getShareUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttachment(\Keosu\DataModel\ArticleModelBundle\Entity\ArticleAttachment $attachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttachment', [$attachments]);

        return parent::addAttachment($attachments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttachment(\Keosu\DataModel\ArticleModelBundle\Entity\ArticleAttachment $attachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttachment', [$attachment]);

        return parent::removeAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', []);

        return parent::getAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttachments($attachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttachments', [$attachments]);

        return parent::setAttachments($attachments);
    }

    /**
     * {@inheritDoc}
     */
    public function addTag(\Keosu\DataModel\ArticleModelBundle\Entity\ArticleTags $tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTag', [$tags]);

        return parent::addTag($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTag(\Keosu\DataModel\ArticleModelBundle\Entity\ArticleTags $tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTag', [$tag]);

        return parent::removeTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags(\Doctrine\Common\Collections\ArrayCollection $tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', [$tags]);

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataModelObjectName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataModelObjectName', []);

        return parent::getDataModelObjectName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReader($reader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReader', [$reader]);

        return parent::setReader($reader);
    }

    /**
     * {@inheritDoc}
     */
    public function getReader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReader', []);

        return parent::getReader();
    }

}
