<?php

namespace Proxies\__CG__\Keosu\DataModel\ArticleModelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArticleAttachment extends \Keosu\DataModel\ArticleModelBundle\Entity\ArticleAttachment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleAttachment' . "\0" . 'name', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleAttachment' . "\0" . 'remote', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleAttachment' . "\0" . 'articleBody', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleAttachment' . "\0" . 'idext', 'orientation'];
        }

        return ['__isInitialized__', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleAttachment' . "\0" . 'name', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleAttachment' . "\0" . 'remote', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleAttachment' . "\0" . 'articleBody', '' . "\0" . 'Keosu\\DataModel\\ArticleModelBundle\\Entity\\ArticleAttachment' . "\0" . 'idext', 'orientation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ArticleAttachment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemote($remote)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemote', [$remote]);

        return parent::setRemote($remote);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemote', []);

        return parent::getRemote();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticleBody(\Keosu\DataModel\ArticleModelBundle\Entity\ArticleBody $articleBody)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticleBody', [$articleBody]);

        return parent::setArticleBody($articleBody);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticleBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticleBody', []);

        return parent::getArticleBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdext($idext)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdext', [$idext]);

        return parent::setIdext($idext);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdext()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdext', []);

        return parent::getIdext();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataModelObjectName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataModelObjectName', []);

        return parent::getDataModelObjectName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', [$path]);

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', []);

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', []);

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', []);

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getThumbWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThumbWebPath', []);

        return parent::getThumbWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadRootDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadRootDir', []);

        return parent::getUploadRootDir();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function createThumb($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createThumb', [$file]);

        return parent::createThumb($file);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrientation($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrientation', [$file]);

        return parent::setOrientation($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrientation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrientation', []);

        return parent::getOrientation();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReader($reader)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReader', [$reader]);

        return parent::setReader($reader);
    }

    /**
     * {@inheritDoc}
     */
    public function getReader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReader', []);

        return parent::getReader();
    }

}
